name: 3dgs-processor
metadata:
  template: 3dgs-processor@0.0.1
services:
  job:
    host: containerapp
    image: ${JOB_IMAGE}
hooks:
  preprovision:
    shell: sh
    run: ./scripts/hooks/preprovision.sh
    continueOnError: true
  postprovision:
    shell: sh
    run: ./scripts/hooks/postprovision.sh
